### ISSUE TITLE
As a MP user, I don't want the plus button to be hidden on mobile

### ISSUE THREAD

**Issue by sddaniels** [Finholt/Masspay#1]
![screen shot 2019-01-11 at 11 42 55 am](https://user-images.githubusercontent.com/1263925/51050359-21ed7a80-1596-11e9-9641-4a726bd67ab6.png)

Desired appearance:
![small-screen](https://user-images.githubusercontent.com/1263925/51050436-6b3dca00-1596-11e9-8a69-67b365c63073.png)

**Comment by Finholt** [comment]
This one was embarrassing. Everything scaled fine when I shrunk the width of the browser window down as far as it would go, but I forgot to check the mobile and responsive views in Chrome Dev Tools as well. Live and learn, I suppose.

**Comment by Finholt** [comment]
![issue1_devretest](https://user-images.githubusercontent.com/14226823/51088640-c05d1580-1727-11e9-8cdf-61be72c0c39b.JPG)

Adding Dev Retest Screenshot
