### ISSUE TITLE
As a MP user, I don't want numbers embedded in text chars to add to the total

### ISSUE THREAD

**Issue by sddaniels** [Finholt/Masspay#3]
Steps to reproduce:
1. enter text such as `bad5input4` into an amount field
2. click out of the text box
3. notice that the total will read `$54.00`

**Comment by Finholt** [comment]
![issu3_devretest](https://user-images.githubusercontent.com/14226823/51088682-63159400-1728-11e9-88a5-90a6d46aac47.JPG)

**Comment by sddaniels** [comment]
Is it possible for you to write a unit test to cover this, as well as issue #4?

**Comment by Finholt** [comment]
> Is it possible for you to write a unit test to cover this, as well as issue #4?

Sure thing!

**Comment by Finholt** [comment]
Unit test cases for this and #4 added in most recent commit

**Comment by sddaniels** [comment]
Love it, thanks!
