### ISSUE TITLE
As a MP user, I want an error message about all invalid input

### ISSUE THREAD

**Issue by sddaniels** [Finholt/Masspay#4]
Steps to reproduce:
1. enter a valid email address and amount in row one
2. in row two, add an invalid amount such as `badinput`
3. do not enter any value into the email address field of row one
4. click submit
5. you should see the success screen

This workflow should result in a validation error.

**Comment by Finholt** [comment]
![issue4_devretest](https://user-images.githubusercontent.com/14226823/51088735-14b4c500-1729-11e9-92c6-1012ea6b4a2b.JPG)

**Comment by Finholt** [comment]
Most recent commit adds unit test cases to address this as asked for in a comment on #3
